### ISSUE TITLE
Add hierarchy flat

### ISSUE THREAD

**Issue by carmeltsadok** [alphawolfteam/friends-user-service#5]
Add `heirarchyFlat` field to each user object in `getById` and `searchByName` functions. 
The `heirarchyFlat` field will be a concatenation of the hierarchy field's string array and the job field.

**Comment by yonatandt** [comment]
You shouldn't close the issue before it enters the `master` or at least the `develop` branch.
In the PR that closes the issue you should write `closes #(issue-number)` and then it should automatically connect with the issue, and if I'm not mistaken also closes it and the PR is merged.

**Comment by yonatandt** [comment]
My mistake. You should link the PR under the `Linked pull requests` in the issue page.
